export const TEXT_CONSTANT = {
  buttonText: 'Lorem ipsum.',
  loremIpsum: 'Lorem ipsum',
  loremIpsum2: 'Lorem ipsum dolor sit amet consectetur.',
  title1: 'Lorem ipsum dolor sit',
  title2: 'Lorem ipsum dolor sit amet consectetur adipiscing elit Ut et.',
  subtitle: 'Lorem ipsum dolor sit',
  calendarText: 'Lorem ipsum dolor sit amet',
  searchPlaceholder: 'Search',
  paragraph2: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa mi. Aliquam in hendrerit urna. Pellentesque sit amet sapien fringilla, mattis ligula consectetur, ultrices mauris. Maecenas vitae mattis tellus. Nullam quis imperdiet augue. Vestibulum auctor ornare leo, non suscipit magna interdum eu. Curabitur pellentesque nibh nibh, at maximus ante fermentum sit amet. Pellentesque commodo lacus at sodales sodales. Quisque sagittis orci ut diam condimentum, vel euismod erat placerat. In iaculis arcu eros, eget tempus orci facilisis id.',
  paragraph: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
};
export const GRID_ITEMS = [
  {
    id: 1,
    title: TEXT_CONSTANT.title1,
    subtitle: TEXT_CONSTANT.subtitle,
    calendarText: TEXT_CONSTANT.calendarText,
    searchPlaceholder: TEXT_CONSTANT.searchPlaceholder,
    paragraph: TEXT_CONSTANT.paragraph,
  },
  {
    id: 2,
    title: TEXT_CONSTANT.title1,
    subtitle: TEXT_CONSTANT.subtitle,
    calendarText: TEXT_CONSTANT.calendarText,
    searchPlaceholder: TEXT_CONSTANT.searchPlaceholder,
    paragraph: TEXT_CONSTANT.paragraph,
  },
  {
    id: 3,
    title: TEXT_CONSTANT.title1,
    subtitle: TEXT_CONSTANT.subtitle,
    calendarText: TEXT_CONSTANT.calendarText,
    searchPlaceholder: TEXT_CONSTANT.searchPlaceholder,
    paragraph: TEXT_CONSTANT.paragraph,
  },
  {
    id: 4,
    title: TEXT_CONSTANT.title1,
    subtitle: TEXT_CONSTANT.subtitle,
    calendarText: TEXT_CONSTANT.calendarText,
    searchPlaceholder: TEXT_CONSTANT.searchPlaceholder,
    paragraph: TEXT_CONSTANT.paragraph,
  },
  {
    id: 5,
    title: TEXT_CONSTANT.title1,
    subtitle: TEXT_CONSTANT.subtitle,
    calendarText: TEXT_CONSTANT.calendarText,
    searchPlaceholder: TEXT_CONSTANT.searchPlaceholder,
    paragraph: TEXT_CONSTANT.paragraph,
  },
  {
    id: 6,
    title: TEXT_CONSTANT.title1,
    subtitle: TEXT_CONSTANT.subtitle,
    calendarText: TEXT_CONSTANT.calendarText,
    searchPlaceholder: TEXT_CONSTANT.searchPlaceholder,
    paragraph: TEXT_CONSTANT.paragraph,
  },
  {
    id: 7,
    title: TEXT_CONSTANT.title1,
    subtitle: TEXT_CONSTANT.subtitle,
    calendarText: TEXT_CONSTANT.calendarText,
    searchPlaceholder: TEXT_CONSTANT.searchPlaceholder,
    paragraph: TEXT_CONSTANT.paragraph,
  },
  {
    id: 8,
    title: TEXT_CONSTANT.title1,
    subtitle: TEXT_CONSTANT.subtitle,
    calendarText: TEXT_CONSTANT.calendarText,
    searchPlaceholder: TEXT_CONSTANT.searchPlaceholder,
    paragraph: TEXT_CONSTANT.paragraph,
  },
  {
    id: 9,
    title: TEXT_CONSTANT.title1,
    subtitle: TEXT_CONSTANT.subtitle,
    calendarText: TEXT_CONSTANT.calendarText,
    searchPlaceholder: TEXT_CONSTANT.searchPlaceholder,
    paragraph: TEXT_CONSTANT.paragraph,
  },
];